name: Update GitHub Activity
on:
  schedule:
    - cron: "0 */12 * * *"  # twice per day
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@v0.4.1
        with:
          COMMIT_MSG: "chore: update activity"
