name: generate-snake
on:
  schedule:
    - cron: "0 0 * * *"   # run daily at 00:00 UTC
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Flaymie
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push to output branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan output
          git --work-tree dist add --all
          git --work-tree dist commit -m "chore: update snake"
          git push origin HEAD:output --force
